Repository johnsson84/HealthCareAB_Backend, pull requests merged in 2025-01, with the labels that each got.

#38 37 forgot password
  pom.xml
  src/main/java/health/care/booking/config/SecurityConfig.java
  src/main/java/health/care/booking/controllers/AuthController.java
  src/main/java/health/care/booking/dto/ResetPasswordRequest.java
  src/main/java/health/care/booking/models/TokenPasswordReset.java
  src/main/java/health/care/booking/respository/TokenPasswordResetRepository.java
  src/main/java/health/care/booking/respository/UserRepository.java
  src/main/java/health/care/booking/services/PasswordResetService.java
  src/test/java/health/care/booking/AvailabilityTest.java
  src/test/java/health/care/booking/BookingApplicationTests.java
  src/test/java/health/care/booking/FindUserByUsernameTest.java
  src/test/java/health/care/booking/SignUpTest.java
Labels: PRIO 3

#52 UserMail & Username @unique
  src/main/java/health/care/booking/controllers/AuthController.java
  src/main/java/health/care/booking/respository/UserRepository.java
Labels: PRIO 2

#57 54 enhetstester backend PasswordResetTest
  src/main/java/health/care/booking/services/PasswordResetService.java
  src/test/java/health/care/booking/BookingApplicationTests.java
  src/test/java/health/care/booking/PasswordResetServiceTest.java
Labels: PRIO 2

#81 Fixed Admin -> Doctor
  src/main/java/health/care/booking/controllers/AppointmentController.java
  src/main/java/health/care/booking/controllers/AvailabilityController.java
  src/main/java/health/care/booking/controllers/FeedbackController.java
  src/main/java/health/care/booking/services/FeedbackService.java
  src/test/java/health/care/booking/FeedbackTests.java
Labels: PRIO 1

#82 63 facilities
  src/main/java/health/care/booking/config/SecurityConfig.java
  src/main/java/health/care/booking/controllers/FacilityController.java
  src/main/java/health/care/booking/dto/FacilityRequest.java
  src/main/java/health/care/booking/dto/UserResponse.java
  src/main/java/health/care/booking/models/Facility.java
  src/main/java/health/care/booking/models/FacilityAddress.java
  src/main/java/health/care/booking/respository/FacilityRepository.java
  src/main/java/health/care/booking/services/FacilityService.java
Labels: PRIO 2

#112 added more enums for conditions
  src/main/java/health/care/booking/models/ConditionsCategory.java
  src/main/java/health/care/booking/services/ConditionsService.java
Labels: PRIO 1
